openapi: 3.0.0
info:
  title: CBDC數位貨幣測試API系統
  description: 資訊安全實驗室銀行端API
  version: 0.1.9
servers:
  - url: http://127.0.0.1:8080
    description: 銀行伺服器
  - url: http://127.0.0.1:8081
    description: 商店伺服器
tags:
- name: "銀行API"
  description: "從銀行領錢與存款的API。"

paths:
  /public-key/user/withdraw:
    get:
      tags:
      - "銀行API"
      summary: 取得銀行公鑰。
      description: 
      responses:
        '200':    # status code
          description: 銀行的RSA公鑰，以Base64格式實現。
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    # type: integer
                    # description: The user ID.
                  PublicKey:
                    type: string
                    description: 銀行的RSA公鑰
                    example: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeE1mcWs1azhSVmRWZGx4MG1ZVGMNCjBoa1c5cDRkaDVOd3JDZnBIdkVXeTh6Y0Y3dEJ6bFJqRzQ0c2RKeUJBSmFmMzNJdFhLUnJVQ2FvaVBTUUxTNkQNCmZPL1liMkc3eDEybVFiZzR5UDVoL1B5WHZJaDh2cEx5S2tHbnF2K3lIQ2YwRTFQZTBkUkFvcXFmdEIvc2V5YUUNClNJWXA4U1hmTVZCNWNGZVNQRXY1MTQ5dEk4cld3RHVBaGlsZWY4LzlBcEdlOXhQVnRiMEFDczB1aHdSSTNvVUwNClZTWmRNWmxWUTNBbEZrN2RSaDdHVno3UGxCVVZQNjJPTXl5RDBiNUxBTVYxOEQ3T2VkZ2pMT1pGc2l5cHh6Q20NCmJVRUFjaE00bjF0R0o1azFBd3U3WDBsakppdXVDdUx6Z29GWGlvQ2pLS2I5L2dRV3h4ZGtrQmxsRzUyb3ROYjUNCjlRSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=

