openapi: 3.0.0
info:
  title: 銀行端API
  description: 資訊安全實驗室銀行端API
  version: 0.1.9
servers:
  - url: http://127.0.0.1:8080
    description: 銀行API
tags:
- name: "pet"
  description: "Everything about your Pets"

paths:
  /public-key/user/withdraw:
    get:
      tags:
      - "pet"
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: header
          name: Access-Control-Allow-Origin
          schema:
            type: string
          required: false
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string